broadcast:
  pre: '&9&lAutoGuardado'
  post: '&9&lAutoGuardado Completado'
broadcastbackup:
  pre: '&9AutoBackuping'
  post: '&9AutoBackup Complete'
broadcastpurge:
  pre: '&9AutoPurging'
  post: '&9AutoPurge Complete'
insufficentpermissions: '&cYou do not have access to that command.'
autorestart:
  restarting: '&9Server is restarting'
  countdown: '&9Server will restart in {SECONDS} seconds'
worldregen:
  kickmessage: '&9Server is regenerating map, please come back later'
